#!/bin/bash

# Základní cesta ke složce s Exercism Ruby úlohami
BASE_DIR="exercism/ruby"

# Kontrola prvního argumentu - příkaz test nebo submit
if [ "$1" = "test" ]; then
  shift # odstraní první argument (test)
  
  # Složka a název testovacího souboru podle názvu úlohy
  TEST_DIR="$BASE_DIR/$1"
  TEST_FILE="${1}_test.rb"
  shift # odstraní druhý argument (název úlohy)
  
  # Spuštění testu s Minitest a pride barvou
  ruby -r minitest/pride "$TEST_DIR/$TEST_FILE" "$@"

elif [ "$1" = "submit" ]; then
  shift # odstraní první argument (submit)
  
  # Složka a název implementačního souboru podle názvu úlohy
  SUBMIT_DIR="$BASE_DIR/$1"
  SUBMIT_FILE="${1}.rb"
  shift # odstraní druhý argument (název úlohy)
  
  # Odeslání řešení na Exercism
  exercism submit "$SUBMIT_DIR/$SUBMIT_FILE" "$@"

else
  # Výpis nápovědy, pokud není zadán správný příkaz
  echo "Usage: ./exe {test|submit} <exercise_name> [additional args]"
fi
